# Generated by Django 5.0.2 on 2025-06-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='iso2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='iso3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'iso2', 'iso3', 'iso_numeric')},
        ),
    ]
